/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
#define M_ITEMS 16
#define M_FUN 16
struct fmenu {char opt; char level; int n; int(***f)(void *farg); void ***arg;};
typedef struct fmenu menu;
#include "remmenu.inc"
	char *GetMessCode(int );
extern	char *_TextCode[];
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
#include "remplus.h"
#include "remdspio.h"
extern	double  pitch;
extern	double  roll;
extern	int         maxmils;
extern	int   corr;
extern	double  p_null   /* pitch offset   */;
extern	double  r_null   /* roll offset   */;
extern	double  p_scale ;
extern	double  r_scale ;
extern	double  cpr    /* pitch/roll align  */;
extern	double  crp;
extern	int   el_null   /* RLD alignment/elev. */;
extern	double  Pscale          /* pitch    */;
extern	double  Pnull         /* coeff.    */;
extern	double  Rscale          /* roll     */;
extern	double  Rnull         /* coeff.    */;
extern	int   Tiltmode        /* Temp coeff select */;
extern	int   pwoff           /* poweroff delay  */;
extern	int         track_delay;
extern	int   GPS_dt          /* GMT offset, hours */;
extern	int   GPS_pdop;
extern	int   dGPS   /* dGPS rate   */;
extern	int   tn_max;
extern	int   tn_min;
extern	double  t_ref;
extern	int   DSPgain[4];
extern	int   key_delay;
extern	int   az_align  /* RLD alignment/azimuth*/;
extern	int   el_align  /* RLD alignment/elevat.*/;
extern	double     az_off   /* az. offset   */;
extern	int   GPS_alt ;
extern	long  GPS_lat ;
extern	long  GPS_lon ;
extern	zone  *Zones,*ZoneId;
extern	int   ZoneUndef,SouthFlag;
extern	char  userpass[] ;
extern	char  syspass[] ;
extern	char  ser_no[] ;
extern	int   heat_temp;
extern	int   shaft;
extern	int   meteo[8][8];
extern	int   meteo_A ;
extern	int   diff_GPS ;
extern	int   GPS_datum;
extern	int   GPS_geo   /* GPS geoid model  */;
extern	int   GPS_dx;
extern	int   GPS_dy;
extern	int   GPS_dz;
extern	int   C100_decl   /* magn. declin.  */;
extern	double  aC100;
extern	double  bC100;
extern	double  cC100;
extern	int   CM_off  ;
extern	int   CM_sect  ;
extern	long  FalseEast ;
extern	long  FalseNorth ;
extern	int   rld_mode   /* general rld port mode*/;
extern	int   aux_mode    ;
extern	int   lcd   ;
extern	int   swvers;
extern	int   Backlit;
extern	int   coordtx;
extern	int   language;
extern	int   RightToLeft;
extern	int         d_mode  ;
extern	int   edit_flag ;
extern	char        time_mode ;
extern	int   Tmax  ;
extern	int   Tmin  ;
extern	int   shaft_data[2];
extern	double      maxgrid     ;
extern	double  SHtoR;
extern	queue       *PIT_task;
extern	queue       *RTC_task;
extern	int   wait_count ;
extern	menu  *curr_menu;;
extern	int   Key,PushKey,PushCount;
extern	char        *error_screen[4],SophieBuff[50];;
extern	char  LcdBuffer[82],LcdBackup[82],LcdExt[32];
extern	double      az_offset;
extern	int   RTCMSize;
extern	long  temp;
extern	char  *library,*fonts,*syspar,eerror;
extern	long  eebott,eetop;
extern	lib         *LL,*Ln,*Lc,*Cn,*Sn,*NAV;
extern	lib   *Lr,*LD,*LPP,*bll,*blll,*crest;
extern	ltype      *LTYPES,*STYPES;
extern	lib         *OBP,*ORG,*NORTH;
extern	command  *CP,*CPM,*GUN,*SYS,*METEO,*LINK,*CPEXE;
extern	int   CountMode;;
extern	RLD         rld;
extern	GPS         gps;
extern	gun   *Guns;
extern	int   lmenu_key;
extern	mscan  *Mscan;
extern	double  GPSn_avrg;
extern	double  GPSdx_avrg;
extern	double  GPSdy_avrg;
extern	double  GPSdz_avrg;
extern	char  RTCMLog[256];
extern	COMPASS     c100;
extern	TCM2  tcm2;
extern	char  JwTx[16],JwRx[16],*Jw,Ibit,JwStat;;
extern	int   JwCount,JwCheck,JwAZ,JwEL,JwR;;
extern	char  pass[] ;
extern	int   r_filt[8],p_filt[8];
extern	int   r_off[8],p_off[8];
extern	int   PITcnt;
extern	rtime  Time;
extern	double  Tamb;
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int smenu(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int EraseAll(void *);
int ret(void *);
int EraseSingle(void *);
int ret(void *);
int ret(void *);
int SaveEE(void *);
int ret(void *);
int LoadEE(void *);
int ret(void *);
int InsertLib(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int s_menu_hold(void *);
int InitObject(void *);
int toLL(void *);
int ret(void *);
int toLL(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int GpsFixClose(void *);
int RLD_enable(void *);
int ret(void *);
int CheckImpl(void *);
int UpdateRtcm(void *);
int CheckPass(void *);
int AlignEcef(void *);
int GpsFixClose(void *);
int RLD_enable(void *);
int MakePos(void *);
int ret(void *);
int GpsFixMode(void *);
int SetGpsRef(void *);
int CheckPass(void *);
int GpsStatus(void *);
int toLL(void *);
int CheckImpl(void *);
int GpsFixInit(void *);
int RLD_disable(void *);
int UpdatePost(void *);
int SaveEE(void *);
int close_srv(void *);
int ret(void *);
int LoadEE(void *);
int close_srv(void *);
int ret(void *);
int last_xyz(void *);
int next_xyz(void *);
int EditX(void *);
int s_menu_hold(void *);
int toLL(void *);
int ret(void *);
int MakeNorth(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int C100_disable(void *);
int RLD_enable(void *);
int ret(void *);
int C100_disable(void *);
int RLD_enable(void *);
int MakeNorth(void *);
int ret(void *);
int s_menu_hold(void *);
int CheckPass(void *);
int InitKVH(void *);
int toLL(void *);
int C100_enable(void *);
int RLD_disable(void *);
int ComputeNorth(void *);
int UpdateNorth(void *);
int SaveEE(void *);
int close_srv(void *);
int ret(void *);
int LoadEE(void *);
int close_srv(void *);
int ret(void *);
int last_xyz(void *);
int next_xyz(void *);
int EditX(void *);
int s_menu_hold(void *);
int LLtoSn(void *);
int ret(void *);
int SntoLL(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int UpdatePost(void *);
int SaveEE(void *);
int close_srv(void *);
int ret(void *);
int LoadEE(void *);
int SntoLL(void *);
int ret(void *);
int toLL(void *);
int LLtoSn(void *);
int traverse(void *);
int close_srv(void *);
int ret(void *);
int LLtoSn(void *);
int NextList(void *);
int LLtoSn(void *);
int LastList(void *);
int LLtoSn(void *);
int LastType(void *);
int LLtoSn(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int LLtoSn(void *);
int ret(void *);
int SntoLL(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int UpdatePost(void *);
int UpdateNorth(void *);
int SaveEE(void *);
int close_srv(void *);
int ret(void *);
int LoadEE(void *);
int SntoLL(void *);
int ret(void *);
int toLL(void *);
int LLtoSn(void *);
int trilaterate(void *);
int close_srv(void *);
int ret(void *);
int LLtoSn(void *);
int NextList(void *);
int LLtoSn(void *);
int LastList(void *);
int LLtoSn(void *);
int LastType(void *);
int LLtoSn(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int LLtoSn(void *);
int ret(void *);
int SntoLL(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int UpdatePost(void *);
int UpdateNorth(void *);
int SaveEE(void *);
int close_srv(void *);
int ret(void *);
int LoadEE(void *);
int SntoLL(void *);
int ret(void *);
int toLL(void *);
int LLtoSn(void *);
int triangulate(void *);
int close_srv(void *);
int ret(void *);
int LLtoSn(void *);
int NextList(void *);
int LLtoSn(void *);
int LastList(void *);
int LLtoSn(void *);
int LastType(void *);
int LLtoSn(void *);
int NextType(void *);
int EditX(void *);
int s_menu_hold(void *);
int MakeTraverse(void *);
int MakeTrilat(void *);
int MakeTriang(void *);
int close_srv(void *);
int ret(void *);
int MakePos(void *);
int MakeNorth(void *);
int ret(void *);
int SaveEE(void *);
int ret(void *);
int LoadEE(void *);
int ret(void *);
int EnableLevel(void *);
int CloseLevel(void *);
int ret(void *);
int DisableLevel(void *);
int CloseLevel(void *);
int ret(void *);
int CloseLevel(void *);
int shutdown_load(void *);
int ret(void *);
int CheckPass(void *);
int ResetLevel(void *);
int CallGun(void *);
int list_on(void *);
int Ack(void *);
int SaveEE(void *);
int ret(void *);
int LoadEE(void *);
int ret(void *);
int next_status(void *);
int list_on(void *);
int last_status(void *);
int list_on(void *);
int NextList(void *);
int list_on(void *);
int LastList(void *);
int list_on(void *);
int comm_enable(void *);
int RLD_enable(void *);
int l_menu_hold(void *);
int list_on(void *);
int RLD_disable(void *);
int list_on(void *);
int UpdateMeteo(void *);
int SaveEE(void *);
int ret(void *);
int LoadEE(void *);
int ret(void *);
int comm_enable(void *);
int l_menu_hold(void *);
int InitMeteo(void *);
int SaveEE(void *);
int ret(void *);
int LoadEE(void *);
int ret(void *);
int comm_enable(void *);
int l_menu_hold(void *);
int InitLevel(void *);
int CheckImpl(void *);
int list_on(void *);
int CheckImpl(void *);
int CheckPass(void *);
int comm_enable(void *);
int l_menu_hold(void *);
int CheckPass(void *);
int MenuView(void *);
int UpdateTarget(void *);
int TargetFromLL(void *);
int RLD_disable(void *);
int list_on(void *);
int ret(void *);
int list_on(void *);
int RLD_disable(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int InitTarget(void *);
int EditX(void *);
int s_menu_hold(void *);
int s_menu_hold(void *);
int SelectTargetType(void *);
int SetDGrid(void *);
int ret(void *);
int SetDMuzz(void *);
int ret(void *);
int SaveCorr(void *);
int ret(void *);
int ret(void *);
int list_on(void *);
int RLD_disable(void *);
int PullMode(void *);
int ret(void *);
int CorrFromLL(void *);
int list_on(void *);
int RLD_disable(void *);
int PullMode(void *);
int ret(void *);
int list_on(void *);
int RLD_disable(void *);
int PullMode(void *);
int ret(void *);
int EditX(void *);
int s_menu_hold(void *);
int InitCorr(void *);
int s_menu_hold(void *);
int UpdateUnit(void *);
int UnitFromLL(void *);
int list_on(void *);
int RLD_disable(void *);
int ret(void *);
int list_on(void *);
int RLD_disable(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int InitUnit(void *);
int EditX(void *);
int s_menu_hold(void *);
int s_menu_hold(void *);
int SelectUnitType(void *);
int TargetToLL(void *);
int RLD_enable(void *);
int PushMode(void *);
int CorrToLL(void *);
int RLD_enable(void *);
int UnitToLL(void *);
int RLD_enable(void *);
int ret(void *);
int Ack(void *);
int ret(void *);
int Nack(void *);
int ret(void *);
int ret(void *);
int Call(void *);
int list_on(void *);
int ret(void *);
int CommandAbort(void *);
int list_on(void *);
int ret(void *);
int list_on(void *);
int ret(void *);
int Ack(void *);
int Nack(void *);
int list_on(void *);
int ret(void *);
int NextTarget(void *);
int DisplBallist(void *);
int LastTarget(void *);
int DisplBallist(void *);
int LastPredict(void *);
int CalcTarget(void *);
int DisplBallist(void *);
int NextPredict(void *);
int CalcTarget(void *);
int DisplBallist(void *);
int list_on(void *);
int CheckTarget(void *);
int CalcTarget(void *);
int DisplBallist(void *);
int SwitchPage(void *);
int EraseCommand(void *);
int list_on(void *);
int ret(void *);
int EraseCommand(void *);
int list_on(void *);
int ret(void *);
int ret(void *);
int CommandCopy(void *);
int list_on(void *);
int ret(void *);
int ret(void *);
int ret(void *);
int list_on(void *);
int CheckTarget(void *);
int CalcTarget(void *);
int DisplBallist(void *);
int SaveEE(void *);
int RLD_enable(void *);
int ret(void *);
int CheckPass(void *);
int InitBallistic(void *);
int next_command(void *);
int list_on(void *);
int last_command(void *);
int list_on(void *);
int next_status(void *);
int list_on(void *);
int last_status(void *);
int list_on(void *);
int comm_enable(void *);
int l_menu_hold(void *);
int list_on(void *);
int list_on(void *);
int library_on(void *);
int clear_screen(void *);
int PushMode(void *);
int clear_screen(void *);
int RLD_disable(void *);
int shutdown_save(void *);
int RLD_enable(void *);
int ret(void *);
int CheckImpl(void *);
int RLD_disable(void *);
int list_on(void *);
int EditX(void *);
int s_menu_hold(void *);
int s_menu_hold(void *);
int SelectLeft(void *);
int InitObject(void *);
int SelectRight(void *);
int NumObj(void *);
int CheckExe(void *);
int s_menu_hold(void *);
int CheckExe(void *);
int s_menu_hold(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int Ack(void *);
int Nack(void *);
int list_on(void *);
int SaveEE(void *);
int RLD_enable(void *);
int ret(void *);
int SwitchPage(void *);
int list_on(void *);
int CheckTarget(void *);
int CalcTarget(void *);
int DisplBallist(void *);
int list_on(void *);
int DisplBallist(void *);
int list_on(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int erase_xyz_s(void *);
int ret(void *);
int erase_xyz_all(void *);
int ret(void *);
int ret(void *);
int EditClose(void *);
int next_xyz(void *);
int EditX(void *);
int EditClose(void *);
int last_xyz(void *);
int EditX(void *);
int EditClose(void *);
int add_xyz(void *);
int EditX(void *);
int EditClose(void *);
int EditX(void *);
int EditY(void *);
int s_menu(void *);
int EditUtm(void *);
int s_menu(void *);
int EditClose(void *);
int EditTL(void *);
int s_menu(void *);
int EditClose(void *);
int s_menu_hold(void *);
int EditX(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
int EditX(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int erase_xyz_s(void *);
int ret(void *);
int erase_xyz_all(void *);
int ret(void *);
int ret(void *);
int EditClose(void *);
int next_xyz(void *);
int EditY(void *);
int EditClose(void *);
int last_xyz(void *);
int EditY(void *);
int EditClose(void *);
int add_xyz(void *);
int EditY(void *);
int EditClose(void *);
int EditY(void *);
int EditX(void *);
int s_menu(void *);
int EditZ(void *);
int s_menu(void *);
int EditClose(void *);
int EditType(void *);
int s_menu(void *);
int EditClose(void *);
int s_menu_hold(void *);
int EditY(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
int EditY(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int erase_xyz_s(void *);
int ret(void *);
int erase_xyz_all(void *);
int ret(void *);
int ret(void *);
int EditClose(void *);
int next_xyz(void *);
int EditZ(void *);
int EditClose(void *);
int last_xyz(void *);
int EditZ(void *);
int EditClose(void *);
int add_xyz(void *);
int EditZ(void *);
int EditClose(void *);
int EditZ(void *);
int EditY(void *);
int s_menu(void *);
int EditClose(void *);
int EditTxt(void *);
int s_menu(void *);
int EditClose(void *);
int s_menu_hold(void *);
int EditZ(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
int EditZ(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int mode_time(void *);
int incr_time_l(void *);
int decr_time_l(void *);
int set_time(void *);
int EditType(void *);
int s_menu(void *);
int EditX(void *);
int s_menu(void *);
int EditTR(void *);
int s_menu(void *);
int s_menu_hold(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int mode_time(void *);
int incr_time_r(void *);
int decr_time_r(void *);
int set_time(void *);
int EditType(void *);
int s_menu(void *);
int EditTL(void *);
int s_menu(void *);
int s_menu_hold(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int sel_txt_r(void *);
int sel_txt_l(void *);
int add_txt(void *);
int EditZ(void *);
int s_menu(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
int EditTxt(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int select_type(void *);
int find_ntyp(void *);
int auto_ntyp(void *);
int EditTL(void *);
int s_menu(void *);
int EditZ(void *);
int s_menu(void *);
int EditY(void *);
int s_menu(void *);
int s_menu_hold(void *);
int EditRefresh(void *);
int EditClose(void *);
int ret(void *);
int EditType(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int set_EL_AZ_R(void *);
int rewrite_LCD(void *);
int ret(void *);
int set_AZ_R_dZ(void *);
int rewrite_LCD(void *);
int ret(void *);
int set_N_E_Z(void *);
int rewrite_LCD(void *);
int ret(void *);
int origin_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int ret(void *);
int origin_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int rewrite_LCD(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int ret(void *);
int origin_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int toLL(void *);
int origin_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int ret(void *);
int bearing_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int rewrite_LCD(void *);
int ret(void *);
int NextList(void *);
int LastList(void *);
int LastType(void *);
int NextType(void *);
int ret(void *);
int point_off(void *);
int ret(void *);
int point_off(void *);
int ret(void *);
int bearing_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int toLL(void *);
int point_on(void *);
int bearing_local(void *);
int rewrite_LCD(void *);
int ret(void *);
int ret(void *);
int set_mils6000(void *);
int rewrite_LCD(void *);
int ret(void *);
int set_mils6400(void *);
int rewrite_LCD(void *);
int ret(void *);
int ret(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int Enter8pt(void *);
int ret(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter8pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter3pt(void *);
int ret(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter3pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Enter3pt(void *);
int AbortKVHcal(void *);
int ret(void *);
int Init8pt(void *);
int Init3pt(void *);
int ret(void *);
int CheckPass(void *);
int C100align(void *);
int CheckPass(void *);
int C100sign(void *);
int CheckPass(void *);
int C100clear(void *);
int ret(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int lmenu(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int SetSerial(void *);
int ReadPwoff(void *);
int ReadTrack(void *);
int SetPass(void *);
int SetPass(void *);
int SetScreen(void *);
int SetTime(void *);
int SetDate(void *);
int ReadGpsoff(void *);
int DiffGps(void *);
int ReadGpsoff(void *);
int ReadGpsLat(void *);
int ReadGpsLon(void *);
int ReadDecl(void *);
int ShowDgrid(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int ShowEncoder(void *);
int ShowPitch(void *);
int ShowRoll(void *);
int ToffTilt(void *);
int TscaleTilt(void *);
int ShowTemp(void *);
int SelDatum(void *);
int SelGeoid(void *);
int GeoOffset(void *);
int GeoOffset(void *);
int GeoOffset(void *);
int ReadPdop(void *);
int GPS_pmode(void *);
int GPS_pmode(void *);
int GPS_pmode(void *);
int GPS_dmode(void *);
int GPS_dmode(void *);
int EnterInt(void *);
int EnterInt(void *);
int EnterLong(void *);
int EnterLong(void *);
int EnterInt(void *);
int SetDSPgain(void *);
int SetDSPgain(void *);
int SetDSPgain(void *);
int SetDSPgain(void *);
int ReadDgps(void *);
int EnterOpt(void *);
int EnterOpt(void *);
int EnterOpt(void *);
int EnterInt(void *);
int EnterOpt(void *);
int EnterOpt(void *);
int RLD_tmode(void *);
int RLD_tmode(void *);
int SetLanguage(void *);
int RLD_irmode(void *);
int RLD_irmode(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int SetHeight(void *);
int AirTemp(void *);
int AirPress(void *);
int AirHum(void *);
int WindSpeed(void *);
int WindDir(void *);
int EditMeteo(void *);
extern	int  comm_par[4];
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int EnterEffect(void *);
int EnterFiretime(void *);
int EnterSect(void *);
int EnterProj(void *);
int EnterFuze(void *);
int EnterCharge(void *);
int EnterRounds(void *);
int EnterInterval(void *);
int EnterTraj(void *);
int EnterFiretime(void *);
int ShowTg(void *);
int ShowTg(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int SetRefDir(void *);
int SetGunref(void *);
int SetGun(void *);
int SetAmm(void *);
int SetPcs(void *);
int SetMass(void *);
int PowderT(void *);
int SetMuzzle(void *);
int EditGun(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int EnterPass(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int smenu(void *);
/*ออออออออออออออออออออออออออออออออออออออออออออออออออออออ*/
int UtmNorth(void *);
int UtmSouth(void *);
int UtmEast(void *);
int UtmWest(void *);
int EditX(void *);
int s_menu(void *);
int EditClose(void *);
int ret(void *);
#define WARNING_P GetMessCode(0)
#define _WARNING_P 0
#define ERROR_P GetMessCode(1)
#define _ERROR_P 1
#define W_ORG_REP GetMessCode(2)
#define _W_ORG_REP 2
#define W_OBP_REP GetMessCode(3)
#define _W_OBP_REP 3
#define W_NORTH_REP GetMessCode(4)
#define _W_NORTH_REP 4
#define W_LIB_EMPTY GetMessCode(5)
#define _W_LIB_EMPTY 5
#define W_SINGLE_ITEM GetMessCode(6)
#define _W_SINGLE_ITEM 6
#define W_ITEM_N_FOUND GetMessCode(7)
#define _W_ITEM_N_FOUND 7
#define W_DGPS_OFF GetMessCode(8)
#define _W_DGPS_OFF 8
#define W_LOW_BATT GetMessCode(9)
#define _W_LOW_BATT 9
#define W_FTIME_ELAPSE GetMessCode(10)
#define _W_FTIME_ELAPSE 10
#define W_RLD_NOMULTG GetMessCode(11)
#define _W_RLD_NOMULTG 11
#define W_CHARGE_MODF GetMessCode(12)
#define _W_CHARGE_MODF 12
#define W_RLD_MULTG GetMessCode(13)
#define _W_RLD_MULTG 13
#define W_RLD_BLOCTG GetMessCode(14)
#define _W_RLD_BLOCTG 14
#define E_OBP_DATA GetMessCode(15)
#define _E_OBP_DATA 15
#define E_ORG_DATA GetMessCode(16)
#define _E_ORG_DATA 16
#define E_NORTH_DATA GetMessCode(17)
#define _E_NORTH_DATA 17
#define E_VOID_DATA GetMessCode(18)
#define _E_VOID_DATA 18
#define E_ILL_DATA GetMessCode(19)
#define _E_ILL_DATA 19
#define E_VOID_TYPE GetMessCode(20)
#define _E_VOID_TYPE 20
#define E_VOID_LIST GetMessCode(21)
#define _E_VOID_LIST 21
#define E_LIB_FULL GetMessCode(22)
#define _E_LIB_FULL 22
#define E_RLD_OFF GetMessCode(23)
#define _E_RLD_OFF 23
#define E_RLD_N_READY GetMessCode(24)
#define _E_RLD_N_READY 24
#define E_NORTH_ORG GetMessCode(25)
#define _E_NORTH_ORG 25
#define E_MAX_VAL GetMessCode(26)
#define _E_MAX_VAL 26
#define E_EMPTY_LIST GetMessCode(27)
#define _E_EMPTY_LIST 27
#define E_NO_TARGET GetMessCode(28)
#define _E_NO_TARGET 28
#define E_NO_STATION GetMessCode(29)
#define _E_NO_STATION 29
#define E_NO_UNIT GetMessCode(30)
#define _E_NO_UNIT 30
#define E_GUN_NOTACT GetMessCode(31)
#define _E_GUN_NOTACT 31
#define E_COMM_PEND GetMessCode(32)
#define _E_COMM_PEND 32
#define E_ITEMR01 GetMessCode(33)
#define _E_ITEMR01 33
#define E_ITEMR02 GetMessCode(34)
#define _E_ITEMR02 34
#define E_ITEMR03 GetMessCode(35)
#define _E_ITEMR03 35
#define E_ITEMM01 GetMessCode(36)
#define _E_ITEMM01 36
#define E_ITEMM02 GetMessCode(37)
#define _E_ITEMM02 37
#define E_ITEMB01 GetMessCode(38)
#define _E_ITEMB01 38
#define E_ITEMB02 GetMessCode(39)
#define _E_ITEMB02 39
#define E_ITEMB03 GetMessCode(40)
#define _E_ITEMB03 40
#define E_NOCOMM GetMessCode(41)
#define _E_NOCOMM 41
#define E_LINKBUSY GetMessCode(42)
#define _E_LINKBUSY 42
#define E_ENDLIST GetMessCode(43)
#define _E_ENDLIST 43
#define E_GPS GetMessCode(44)
#define _E_GPS 44
#define E_NOT_BT GetMessCode(45)
#define _E_NOT_BT 45
#define E_NOT_TG GetMessCode(46)
#define _E_NOT_TG 46
#define E_NOT_MT GetMessCode(47)
#define _E_NOT_MT 47
#define E_NOT_MTG GetMessCode(48)
#define _E_NOT_MTG 48
#define E_1PT_ALLW GetMessCode(49)
#define _E_1PT_ALLW 49
#define E_3PT_ALLW GetMessCode(50)
#define _E_3PT_ALLW 50
#define E_8PT_ALLW GetMessCode(51)
#define _E_8PT_ALLW 51
#define E_FIX_FTIME GetMessCode(52)
#define _E_FIX_FTIME 52
#define E_ILL_PASS GetMessCode(53)
#define _E_ILL_PASS 53
#define E_TARG_OVERR GetMessCode(54)
#define _E_TARG_OVERR 54
#define E_TARG_UNDERR GetMessCode(55)
#define _E_TARG_UNDERR 55
#define E_TARG_OUTR GetMessCode(56)
#define _E_TARG_OUTR 56
#define E_M01EQM02 GetMessCode(57)
#define _E_M01EQM02 57
#define E_R01EQR02 GetMessCode(58)
#define _E_R01EQR02 58
#define E_USED_BY GetMessCode(59)
#define _E_USED_BY 59
#define E_CREST GetMessCode(60)
#define _E_CREST 60
#define M_OBP_DATA GetMessCode(61)
#define _M_OBP_DATA 61
#define M_OBJ_DEL GetMessCode(62)
#define _M_OBJ_DEL 62
#define M_OBJ_INS GetMessCode(63)
#define _M_OBJ_INS 63
#define M_OBJ_REP GetMessCode(64)
#define _M_OBJ_REP 64
#define M_NUM_ON GetMessCode(65)
#define _M_NUM_ON 65
#define M_UPP_ON GetMessCode(66)
#define _M_UPP_ON 66
#define M_LOW_ON GetMessCode(67)
#define _M_LOW_ON 67
#define M_LIST_UPDAT GetMessCode(68)
#define _M_LIST_UPDAT 68
#define M_GUN_UPDAT GetMessCode(69)
#define _M_GUN_UPDAT 69
#define M_COMM_READY GetMessCode(70)
#define _M_COMM_READY 70
#define M_COMM_END GetMessCode(71)
#define _M_COMM_END 71
#define M_COMM_REJ GetMessCode(72)
#define _M_COMM_REJ 72
#define M_COMM_ABORT GetMessCode(73)
#define _M_COMM_ABORT 73
#define M_LASER_ON GetMessCode(74)
#define _M_LASER_ON 74
#define M_LASER_OFF GetMessCode(75)
#define _M_LASER_OFF 75
#define M_METEO_INI GetMessCode(76)
#define _M_METEO_INI 76
#define M_METEO_UPDT GetMessCode(77)
#define _M_METEO_UPDT 77
#define M_WAITING GetMessCode(78)
#define _M_WAITING 78
#define M_SAVE_LIB GetMessCode(79)
#define _M_SAVE_LIB 79
#define M_LOAD_LIB GetMessCode(80)
#define _M_LOAD_LIB 80
#define CO_UNDEF GetMessCode(81)
#define _CO_UNDEF 81
#define BT_UNDEF GetMessCode(82)
#define _BT_UNDEF 82
#define TG_UNDEF GetMessCode(83)
#define _TG_UNDEF 83
#define RP_UNDEF GetMessCode(84)
#define _RP_UNDEF 84
#define OP_UNDEF GetMessCode(85)
#define _OP_UNDEF 85
#define CR_UNDEF GetMessCode(86)
#define _CR_UNDEF 86
#define INF_HQ GetMessCode(87)
#define _INF_HQ 87
#define ART_HQ GetMessCode(88)
#define _ART_HQ 88
#define ARM_HQ GetMessCode(89)
#define _ARM_HQ 89
#define TG_INF GetMessCode(90)
#define _TG_INF 90
#define TG_ART GetMessCode(91)
#define _TG_ART 91
#define TG_ARM GetMessCode(92)
#define _TG_ARM 92
#define T_POSITION GetMessCode(93)
#define _T_POSITION 93
#define T_REF_NORTH GetMessCode(94)
#define _T_REF_NORTH 94
#define T_REFP1 GetMessCode(95)
#define _T_REFP1 95
#define T_REFP2 GetMessCode(96)
#define _T_REFP2 96
#define T_REFP3 GetMessCode(97)
#define _T_REFP3 97
#define T_MEAS1 GetMessCode(98)
#define _T_MEAS1 98
#define T_MEAS2 GetMessCode(99)
#define _T_MEAS2 99
#define T_MEAS3 GetMessCode(100)
#define _T_MEAS3 100
#define T_BEAR1 GetMessCode(101)
#define _T_BEAR1 101
#define T_BEAR2 GetMessCode(102)
#define _T_BEAR2 102
#define T_BEAR3 GetMessCode(103)
#define _T_BEAR3 103
#define T_ESTIMATED GetMessCode(104)
#define _T_ESTIMATED 104
#define T_PITCH_ROLL GetMessCode(105)
#define _T_PITCH_ROLL 105
#define T_LEVEL_ON GetMessCode(106)
#define _T_LEVEL_ON 106
#define T_LEVEL_OFF GetMessCode(107)
#define _T_LEVEL_OFF 107
#define T_PASSW GetMessCode(108)
#define _T_PASSW 108
#define T_FMODE_0 GetMessCode(109)
#define _T_FMODE_0 109
#define T_FMODE_1 GetMessCode(110)
#define _T_FMODE_1 110
#define GUN_BATTERY GetMessCode(111)
#define _GUN_BATTERY 111
#define GUN_PLT1 GetMessCode(112)
#define _GUN_PLT1 112
#define GUN_PLT2 GetMessCode(113)
#define _GUN_PLT2 113
#define GUN_REFNO GetMessCode(114)
#define _GUN_REFNO 114
#define COMM_MESSAGE GetMessCode(115)
#define _COMM_MESSAGE 115
#define GUN_MESS GetMessCode(116)
#define _GUN_MESS 116
#define METEO_MESSAGE GetMessCode(117)
#define _METEO_MESSAGE 117
#define MESS_DEST GetMessCode(118)
#define _MESS_DEST 118
#define MESS_SOURCE GetMessCode(119)
#define _MESS_SOURCE 119
#define TRAJ_HIGH GetMessCode(120)
#define _TRAJ_HIGH 120
#define TRAJ_LOW GetMessCode(121)
#define _TRAJ_LOW 121
#define EFF_DESTROY GetMessCode(122)
#define _EFF_DESTROY 122
#define EFF_NEUTRALIZE GetMessCode(123)
#define _EFF_NEUTRALIZE 123
#define EFF_SMOKE GetMessCode(124)
#define _EFF_SMOKE 124
#define EFF_ILLUMINATE GetMessCode(125)
#define _EFF_ILLUMINATE 125
#define FIRE_HOLD GetMessCode(126)
#define _FIRE_HOLD 126
#define FIRE_IMM GetMessCode(127)
#define _FIRE_IMM 127
#define FIRE_WHEN_READY GetMessCode(128)
#define _FIRE_WHEN_READY 128
#define MESS_UNDEF GetMessCode(129)
#define _MESS_UNDEF 129
#define MESS_PEND GetMessCode(130)
#define _MESS_PEND 130
#define MESS_ACK GetMessCode(131)
#define _MESS_ACK 131
#define MESS_NACK GetMessCode(132)
#define _MESS_NACK 132
#define MESS_ABORT GetMessCode(133)
#define _MESS_ABORT 133
#define MONTH_1 GetMessCode(134)
#define _MONTH_1 134
#define MONTH_2 GetMessCode(135)
#define _MONTH_2 135
#define MONTH_3 GetMessCode(136)
#define _MONTH_3 136
#define MONTH_4 GetMessCode(137)
#define _MONTH_4 137
#define MONTH_5 GetMessCode(138)
#define _MONTH_5 138
#define MONTH_6 GetMessCode(139)
#define _MONTH_6 139
#define MONTH_7 GetMessCode(140)
#define _MONTH_7 140
#define MONTH_8 GetMessCode(141)
#define _MONTH_8 141
#define MONTH_9 GetMessCode(142)
#define _MONTH_9 142
#define MONTH_10 GetMessCode(143)
#define _MONTH_10 143
#define MONTH_11 GetMessCode(144)
#define _MONTH_11 144
#define MONTH_12 GetMessCode(145)
#define _MONTH_12 145
#define DAY_1 GetMessCode(146)
#define _DAY_1 146
#define DAY_2 GetMessCode(147)
#define _DAY_2 147
#define DAY_3 GetMessCode(148)
#define _DAY_3 148
#define DAY_4 GetMessCode(149)
#define _DAY_4 149
#define DAY_5 GetMessCode(150)
#define _DAY_5 150
#define DAY_6 GetMessCode(151)
#define _DAY_6 151
#define DAY_7 GetMessCode(152)
#define _DAY_7 152
#define TYPE_OP GetMessCode(153)
#define _TYPE_OP 153
#define TYPE_CO GetMessCode(154)
#define _TYPE_CO 154
#define TYPE_BT GetMessCode(155)
#define _TYPE_BT 155
#define TYPE_TG GetMessCode(156)
#define _TYPE_TG 156
#define TYPE_MT GetMessCode(157)
#define _TYPE_MT 157
#define TYPE_CR GetMessCode(158)
#define _TYPE_CR 158
#define TYPE_RP GetMessCode(159)
#define _TYPE_RP 159
#define KEY_NUMERIC GetMessCode(160)
#define _KEY_NUMERIC 160
#define KEY_ALPHA0 GetMessCode(161)
#define _KEY_ALPHA0 161
#define KEY_ALPHA1 GetMessCode(162)
#define _KEY_ALPHA1 162
#define KEY_ALPHA2 GetMessCode(163)
#define _KEY_ALPHA2 163
#define KEY_ALPHA3 GetMessCode(164)
#define _KEY_ALPHA3 164
#define M_METER GetMessCode(165)
#define _M_METER 165
#define M_HOUR GetMessCode(166)
#define _M_HOUR 166
#define M_SECOND GetMessCode(167)
#define _M_SECOND 167
#define M_AZIMUTH GetMessCode(168)
#define _M_AZIMUTH 168
#define M_BEARING GetMessCode(169)
#define _M_BEARING 169
#define M_ROUNDS GetMessCode(170)
#define _M_ROUNDS 170
#define ABBRV_NORTH GetMessCode(171)
#define _ABBRV_NORTH 171
#define ABBRV_SOUTH GetMessCode(172)
#define _ABBRV_SOUTH 172
#define ABBRV_EAST GetMessCode(173)
#define _ABBRV_EAST 173
#define ABBRV_WEST GetMessCode(174)
#define _ABBRV_WEST 174
extern	char *_MenuCode[];
extern	char *_MenuHead[];
